### PR TITLE
Allow missing map fields to map to None

### LINKED ISSUE #2: MapVisitor's missing_field doesn't handle Option properly
MapVisitor's [missing_field implementation](https://github.com/arcnmx/serde-value/blob/master/src/lib.rs#L418) currently delegates to deserializing from a `Value::Unit`, but this unfortunately doesn't work for the use case of having an `Optional<Foo>` field that will be set to `None` if the field isn't provided, since `Optional`'s `Visitor` only handles `visit_some` and `visit_none`.

missing_field's default implementation gets around this by using a `ValueDeserializer` for `()`, which pays attention to the `visit_option` hint: https://github.com/serde-rs/serde/blob/master/serde/src/de/value.rs#L109-L119.

serde_json does something similar but with a local Deserializer: https://serde-rs.github.io/json/src/serde_json/value.rs.html#951 for some reason.

### PR DESCRIPTION
**Pull request by sfackler**
This is the same approach that serde-json and serde-yaml take.

Closes #2

### CODE REVIEW

**Comment by arcnmx** [comment]
I'm still a bit iffy on this since `#[serde(default)]` exists, so types with optional arguments can always opt into it... Note that the toml crate, unlike json/yaml, doesn't act like this. On the other hand, there's probably little harm in allowing it, and any types that can be deserialized from `unit` could've just been provided as `null` in the json anyway (not possible in toml I guess)...

**Comment by sfackler** [comment]
@alexcrichton - is the toml-rs behavior here intentional? It doesn't look from a quick overview like there are any explicit tests for this.

**Comment by alexcrichton** [comment]
Ah unfortunately I'm still not quite at the point where I can read serde code and understand what it's doing, what behavior are you referring to?

**Comment by sfackler** [comment]
```rust
#[derive(Deserialize)]
struct Foo {
    bar: i32,
    baz: Option<String>,
}
```

```toml
bar = 1
# baz = "hi"
```

Basically, would you expect that a `Foo` could deserialize from TOML input that does not define a `baz` field.

**Comment by alexcrichton** [comment]
Yeah, that behavior is indeed intentional

**Comment by arcnmx** [comment]
That's what `#[serde(default)]` is for! I find the behaviour of serde-json surprising, personally.

**Comment by arcnmx** [comment]
Hm, wait, I may be mistaken...

**Comment by sfackler** [comment]
So `#[serde(default)]` will do this, but it is unfortunate that a Deserializable impl written without them will work when deserializing directly from JSON, but not when deserializing from a Value deserialized from JSON.

**Comment by arcnmx** [comment]
I feel like it's too much magic, but the serde world disagrees, and until we get some sort of "strictness" mode... It's harmless enough to include.

**Comment by sfackler** [comment]
Thanks! I definitely agree that there's a somewhat unspecified set of "magicness" that would be good to nail down across the serde ecosystem.

**Comment by sfackler** [comment]
Could you publish a new release to crates.io when you have a chance?

**Comment by arcnmx** [comment]
Done!

**Pull request merged**
