### PR TITLE
Add to_value

### PR DESCRIPTION
**Pull request by sfackler**
Also upgrade ordered-float while we're in here.

### CODE REVIEW

**Comment by arcnmx** [comment]
Awesome! Would you mind adding a simple test case for `to_value`? Just something like adding to the `smoke_test` and checking for equality of `to_value(&value)` should be enough.

**Comment by sfackler** [comment]
Updated!

**Comment by arcnmx** [comment]
Thanks!

**Comment by arcnmx** [comment]
Pushed to crates.io, minor bump because I think I didn't see any breakage but I could be wrong..!

**Pull request merged**
